apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceappmazzie-deployment
  labels:
    app: myinsuranceappmazzie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myinsuranceappmazzie
  template:
    metadata:
      labels:
        app: myinsuranceappmazzie
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: myinsuranceappmazzie-deployment-az
        image: hackathonimages.azurecr.io/myinsuranceappmazzie:v8
        ports:
        - name: http
          containerPort: 5000